Projet_tchat/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tchat.Core.DTO;
using Tchat.Infrastructure.dal;
using Tchat.Infrastructure.DAL;

namespace Projet_tchat.Controllers
{
    public class LoginController : Controller
    {
        private IRepository db;

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Connexion(String log_username, String log_password)
        {
         
           LoginDTO logg = db.Authentifier(log_username,log_password);
            if (logg == null)
            {
                return HttpNotFound();
            } 
            
            String premierCaractere = logg.name.Substring(0,1);
            String premierCar = logg.firstname.Substring(0, 1);
         
           Session["CarNom"] = premierCaractere;
           Session["CarPrenom"] = premierCar;
           Session["Nom"] = logg.name;
           Session["Prenom"] = logg.firstname;
           Session["ID"] = logg.id_user;

           return RedirectToAction("Index","Home");
           

        }

        public ActionResult Deco()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }

        public LoginController()
        {
            db = new Repository();
        }

    }
}

Projet_tchat/Controllers/UtilisateursController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tchat.Core.DTO;
using Tchat.Core.Models;
using Tchat.Infrastructure.dal;
using Tchat.Infrastructure.DAL;

namespace Projet_tchat.Controllers
{
    public class UtilisateursController : Controller
    {
        // GET: Utilisateurs
        private IRepository db;
        private TchatContext bdd = new TchatContext();



        // GET: PostCtrler
     

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userID,name,firstname,email,password,date_create,modification_date")] User user)
        {
            if (ModelState.IsValid)
            {
                bdd.User.Add(user);
                bdd.SaveChanges();
                return RedirectToAction("Index","Login");
            }

            return View(user);
        }

        public ActionResult Edit()
        {
            if (Session["ID"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = bdd.User.Find(Session["ID"]);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "userID,name,firstname,email,password,date_create,modification_date")] User user)
        {
            if (ModelState.IsValid)
            {
                bdd.Entry(user).State = EntityState.Modified;
                bdd.SaveChanges();

                String premierCaractere = user.name.Substring(0, 1);
                String premierCar = user.firstname.Substring(0, 1);
                Session["CarNom"] = premierCaractere;
                Session["CarPrenom"] = premierCar;
                Session["Nom"] = user.name;
                Session["Prenom"] = user.firstname;

                return RedirectToAction("Index","Home");
            }
            return View(user);
        }


        public ActionResult Delete()
        {
            if (Session["ID"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = bdd.User.Find(Session["ID"]);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed()
        {
            User user = bdd.User.Find(Session["ID"]);
            bdd.User.Remove(user);
            bdd.SaveChanges();
            return RedirectToAction("Deco","Login");
        }







        public UtilisateursController()
        {
            db = new Repository();
        }
    }
}

Projet_tchat/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
}
<html>
<head> <title> Talks</title></head>
<body>


    <div class="page login-page">
        <div class="container">
            <div class="form-outer text-center d-flex align-items-center">
                <div class="form-inner">
                    <div class="logo text-uppercase"><span>Se</span><strong class="text-primary">Connecter</strong></div>
                    <p>Ici vous pouvez vous connecter à Talks,partagez, communiquez et amusez-vous !</p>
                    <form method="get" class="text-right form-validate">
                        <div class="form-row text-center">
                            <div class="form-group col-md-11">
                                <input id="login-username" type="text" name="loginUsername" required data-msg="Mail requis" class="input-material">
                                <label for="login-username" class="label-material">Mail</label>
                            </div>
                            <br />
                            <br />
                            <br />


                            <div class="form-group col-md-11">

                                <input id="login-password" type="password" name="loginPassword" required data-msg="Mot de passe requis" class="input-material">

                                <label for="login-password" class="label-material">Mot de passe</label>

                            </div>

                            <div class="form-group col-md-1">
                                <button type="button" id="pwdlog" class="btn btn-light" onclick="togglePwd('login-password');"><i class="far fa-eye" align="center"></i></button>
                            </div>
                            <br />
                            <br />
                            <br />
                            <br />
                            <div class="form-group col-md-12 text-center">
                                <!-- <a id="login" class="btn btn-primary">Login</a>   -->
                                <input type="submit" class="btn btn-primary" id="login" value="Se connecter"/>
                                <!-- This should be submit button but I replaced it with <a> for demo purposes-->
                            </div>
                        </div>
</form>
                    <!-- <a href="#" class="forgot-pass">Forgot Password?</a>--><small>Vous n'avez pas de compte? </small>@Html.ActionLink("S'inscrire", "Create", "Utilisateurs")
                </div>

            </div>
        </div>
    </div>
   
    <script>
        "use strict";
        function togglePwd(id) {
            var x = document.getElementById(id);
            x.type = (x.type === "password") ? "text" : "password";
        }
    </script>
</body>
</html>