Projet_tchat/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tchat.Core.Models;
using Tchat.Infrastructure.DAL;

namespace Projet_tchat.Controllers
{
    public class CategoriesController : Controller
    {
        private TchatContext db = new TchatContext();

        // GET: Categories
        public ActionResult Index()
        {
            if (Session["ID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                if(Session["Nom"].Equals("Mandeville"))
                {
                    return View(db.Category.ToList());
                }
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {  if (Session["ID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                if (Session["Nom"].Equals("Mandeville"))
                {
                    return View();
                }
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Categories/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "categoryID,category_title")] Category category)
        {
          
                    if (ModelState.IsValid)
                    {
                        db.Category.Add(category);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(category);
      
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["ID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                if(Session["Nom"].Equals("Mandeville"))
                {
                        if (id == null)
                             {
                                   return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                              }
                               Category category = db.Category.Find(id);
                           if (category == null)
                           {
                               return HttpNotFound();
                            }
                            return View(category);
                }
                return RedirectToAction("Index", "Home");

            }
        }

        // POST: Categories/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "categoryID,category_title")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["ID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                if (Session["Nom"].Equals("Mandeville"))
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Category category = db.Category.Find(id);
                    if (category == null)
                    {
                        return HttpNotFound();
                    }
                    return View(category);
                }
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Category.Find(id);
            db.Category.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projet_tchat/Controllers/ContactController.cs
using Projet_tchat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Documents;
using Tchat.Core.DTO;
using Tchat.Core.Models;
using Tchat.Infrastructure.dal;
using Tchat.Infrastructure.DAL;

namespace Projet_tchat.Controllers
{
    public class ContactController : Controller
    {
        private TchatContext db = new TchatContext();
        private IRepository bdd;
        // GET: Contact
        public ActionResult Index()
        {
            List<UserDTO> liste_contact = bdd.liste();
            List<ContactVM> Contact_message = new List<ContactVM>();

            foreach (var item in liste_contact)
            {
                ContactVM temp = new ContactVM();
                temp.userID = item.UserID;
                temp.nom = item.nom;
                temp.prenom = item.prenom;
                List<MessageDTO> dernier_message = bdd.message((int)Session["ID"], item.UserID);
             
                    MessageDTO temporaire = dernier_message.LastOrDefault();
                    temp.message = temporaire;
                  //  System.Diagnostics.Debug.WriteLine("Message : " + temp.message);
                

                Contact_message.Add(temp);
            }

            if (Session["Nom"] == null)
            {
                return RedirectToAction("Index", "Login");

            }
            else
            {
                return View(Contact_message);
            }

        }

        
        public ActionResult MesMessages(int id)
        {
            if (Session["Nom"] == null)
            {
                return RedirectToAction("Index", "Login");

            }
            else
            {
               Session["ID_send"] = id;
            List<MessageDTO> liste = bdd.message((int)Session["ID"], id);
                // RECUPERER LE NOM + PRENOM POUR L'AFFICHER DANS "MES MESSAGES"
                UserDTO us = bdd.utilisateurmessage(id);
                Session["nom_message"] = us.nom;
                Session["prenom_message"] = us.prenom;

            return View();
            }


            
        }

        public JsonResult MessagesByID(int id)
        {
            if (Session["Nom"] == null)
            {
                RedirectToAction("Index", "Login");
                return null;

            }
            else
            {
                Session["ID_send"] = id;
                List<MessageDTO> liste = bdd.message((int)Session["ID"], id);

                return Json(liste);
            }



        }


        [HttpPost]
      
        public void createmessage(Private_message p)
        {
            int i = (int)Session["ID"];
            int id = (int)Session["ID_send"];
           

            Private_message pm = new Private_message { id_sender = i, id_recepient = id, date_message = DateTime.Now, content = p.content };
            db.Private_message.Add(pm);
            db.SaveChanges();


        }

        public ContactController()
        {
            bdd = new Repository();
        }

    }
}

Projet_tchat/Controllers/PostController.cs
using Projet_tchat.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tchat.Core.DTO;
using Tchat.Core.Models;
using Tchat.Infrastructure.dal;
using Tchat.Infrastructure.DAL;

namespace Projet_tchat.Controllers
{
    public class PostController : Controller
    {
        private IRepository db;
        private TchatContext bdd = new TchatContext();


        //AFFICHAGE DE TOUS LES POSTS
        public ActionResult Index()
        {

            List<PostDTO> Lesposts = db.AllPost();
            List<int> Liste_post_ID = (from r in Lesposts select r.PostID).ToList();
            List<CommentDTO> LesCommentaires = db.ListeCommentaire(Liste_post_ID);
            List<PostVM> All_Post_Comment = new List<PostVM>();

            foreach (var item in Lesposts)
            {
                PostVM temp = new PostVM();
                temp.PostID = item.PostID;

                temp.nom = item.nom;
                temp.prenom = item.prenom;
                temp.content = item.content;

                temp.date_create = item.date_create;
                temp.Comments = LesCommentaires.Where(c => c.PostID == temp.PostID).ToList();

                All_Post_Comment.Add(temp);
            }

            if (Session["Nom"] == null)
            {
                return RedirectToAction("Index", "Login");

            }
            else
            {
                return View(All_Post_Comment);
            }


        }

        //VOIR MES POSTS
        public ActionResult MesPosts()
        {

            if (Session["Nom"] == null)
            {
                return RedirectToAction("Index", "Login");

            }
            else
            {


                List<PostDTO> Lesposts = db.postByUserID((int)Session["ID"]);
                List<int> Liste_post_ID = (from r in Lesposts select r.PostID).ToList();
                List<CommentDTO> LesCommentaires = db.ListeCommentaire(Liste_post_ID);
                List<PostVM> All_Post_Comment = new List<PostVM>();

                foreach (var item in Lesposts)
                {
                    PostVM temp = new PostVM();
                    temp.PostID = item.PostID;
                    temp.nom = item.nom;
                    temp.prenom = item.prenom;
                    temp.content = item.content;

                    temp.date_create = item.date_create;
                    temp.Comments = LesCommentaires.Where(c => c.PostID == temp.PostID).ToList();

                    All_Post_Comment.Add(temp);
                }
                System.Diagnostics.Debug.WriteLine("ID USER" + LesCommentaires);
                return View(All_Post_Comment);
            }




        }

        //MODIFICATION
        public ActionResult Edit(int id)
        {
            MONPOSTIDDTO unpost = db.ididepost(id);

            if (unpost.userID == (int)Session["ID"])
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Post post = bdd.Post.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                ViewBag.categoryID = new SelectList(bdd.Category, "categoryID", "category_title", post.categoryID);
                return View(post);


            }
            else
            {
                return View("Index");
            }




        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "postID,userID,categoryID,content,date_create,modification_date,nb_like")] Post post)
        {
            if (ModelState.IsValid)
            {
                bdd.Entry(post).State = EntityState.Modified;
                bdd.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categoryID = new SelectList(bdd.Category, "categoryID", "category_title", post.categoryID);
            return View(post);



        }

        // DELETE
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = bdd.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = bdd.Post.Find(id);
            bdd.Post.Remove(post);
            bdd.SaveChanges();
            return RedirectToAction("Index");
        }

        //CREATION
        public ActionResult Create()
        {
            ViewBag.categoryID = new SelectList(bdd.Category, "categoryID", "category_title");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "postID,userID,categoryID,content,date_create,modification_date,status,nb_like")] Post post)
        {
            if (ModelState.IsValid)
            {
                bdd.Post.Add(post);
                bdd.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categoryID = new SelectList(bdd.Category, "categoryID", "category_title", post.categoryID);
            return View(post);
        }

        [HttpPost]
        [ValidateInput(false)]
        public void createpost(Comment p)
        {

            int i = (int)Session["ID"];
            // System.Diagnostics.Debug.WriteLine("ID USER" +i);
            int id_post = (int)p.postID;
            //  System.Diagnostics.Debug.WriteLine("ID POST"+id_post);

            Comment c = new Comment { postID = id_post, userID = i, content = p.content };
            bdd.Comment.Add(c);
            bdd.SaveChanges();


        }

        public JsonResult GetPostContent()
        {
            List<PostDTO> Lesposts = db.AllPost();
            return Json(Lesposts);
        }

        public JsonResult GetPostByIDUser()
        {
            List<PostDTO> Lesposts = db.postByUserID((int)Session["ID"]);
            return Json(Lesposts);
        }





        public PostController()
        {
            db = new Repository();
        }



    }
}

Projet_tchat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Talks</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>





<!-- Bootstrap CSS-->
<link rel="stylesheet" href="~/FrontEnd/vendor/bootstrap/css/bootstrap.min.css">
<!-- Font Awesome CSS-->
<link rel="stylesheet" href="~/FrontEnd/vendor/font-awesome/css/font-awesome.min.css">
<!-- Fontastic Custom icon font-->
<link rel="stylesheet" href="~/FrontEnd/css/fontastic.css">
<!-- Google fonts - Roboto -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
<!-- jQuery Circle-->
<link rel="stylesheet" href="~/FrontEnd/css/grasp_mobile_progress_circle-1.0.0.min.css">
<!-- Custom Scrollbar-->
<link rel="stylesheet" href="~/FrontEnd/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">
<!-- theme stylesheet-->
<link rel="stylesheet" href="~/FrontEnd/css/style.default.css" id="theme-stylesheet">
<!-- Custom stylesheet - for your changes-->
<link rel="stylesheet" href="~/FrontEnd/css/custom.css">
<!-- Favicon-->
<link rel="shortcut icon" href="~/FrontEnd/img/favicon.ico">
<!-- Tweaks for older IEs-->
<link rel="stylesheet" href="~/FrontEnd/css/custom.css">
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
@RenderSection("Styles", false)






<body>
    <!-- Side Navbar -->
    <nav class="side-navbar  ">
        <div class="side-navbar-wrapper ">
            <!-- Sidebar Header    -->
            <div class="sidenav-header d-flex align-items-center justify-content-center ">
                <!-- User Info-->
                <div class="sidenav-header-inner text-center">


                    <h2 class="h5">@Session["Nom"] @Session["Prenom"] </h2>
                </div>
                <!-- Small Brand information, appears on minimized sidebar-->
                <div class="sidenav-header-logo"><a href="@Url.Action("Index", "Home")" class="brand-small text-center"> <strong>@Session["CarPrenom"]</strong><strong class="text-primary">@Session["CarNom"]</strong></a></div>
            </div>
            <!-- Sidebar Navigation Menus-->
            <div class="main-menu">
                <h5 class="sidenav-heading">Main</h5>
                <ul id="side-main-menu" class="side-menu list-unstyled">

                    @if (Session["Nom"] == null)
                    {
                              <li> <a href="@Url.Action("Create", "Utilisateurs")"><i class="icon-user"></i>S'inscrire</a></li>
                              <li> <a href="@Url.Action("Index", "Login")"><i class="icon-user"></i>Se connecter </a></li>
                    }
                    else
                    {
                              <li> <a href="@Url.Action("Index", "Home")"><i class="icon-home"></i> Accueil</a></li>
                              <li> <a href="@Url.Action("Index", "Contact")"><i class="icon-mail"></i>Message </a></li>
                              if (Session["Nom"].Equals("Mandeville"))
                              {
                                    <li> <a href="@Url.Action("Index", "Categories")"><i class="icon-grid"></i>Categories </a></li> 
                              }




                              <li>
                                <a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Posts </a>
                                <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                                     <li> <a href="@Url.Action("Create", "Post")"><i class="icon-flask"></i>Créer </a></li>
                                     <li> <a href="@Url.Action("Index", "Post")"><i class="icon-flask"></i>Posts </a></li>
                                     <li> <a href="@Url.Action("MesPosts", "Post")"><i class="icon-flask"></i>Mes Posts </a></li>
                                </ul>

                              </li>
                    }

                </ul>
            </div>

            @if (Session["Nom"] != null)
            {


                    <div class="admin-menu">
                    <h5 class="sidenav-heading">Compte</h5>
                    <ul id="side-admin-menu" class="side-menu list-unstyled">
                        <li> <a href="@Url.Action("Edit", "Utilisateurs")"><i class="icon-user"></i>Compte</a></li>
                        <li> <a href="@Url.Action("Deco", "Login")"><i class="fa fa-sign-out"></i>Se déconnecter</a></li>

                    </ul>
                    </div>      
            }
        </div>
    </nav>
    <div class="page" id="lebody">
        <!-- navbar-->
        <header class="header">
            <nav class="navbar" id="barre">
                <div class="container-fluid ">
                    <div class="navbar-holder d-flex align-items-center justify-content-between">
                        <div class="navbar-header">
                            <a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a><a href="@Url.Action("Index", "Home")" class="navbar-brand">
                                <div class="brand-text d-none d-md-inline-block"><strong class="text-primary">Talks</strong></div>
                            </a>
                        </div>

                    </div>
                </div>
            </nav><br />
            <br />
            <br />
            <br />
            <br />
        </header>

        @RenderBody()

    </div>



</body>

<!-- JavaScript files-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<script src="~/FrontEnd/vendor/jquery/jquery.min.js"></script>
<script src="~/FrontEnd/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/FrontEnd/js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
<script src="~/FrontEnd/vendor/jquery.cookie/jquery.cookie.js"></script>
<script src="~/FrontEnd/vendor/chart.js/Chart.min.js"></script>
<script src="~/FrontEnd/vendor/jquery-validation/jquery.validate.min.js"></script>
<script src="~/FrontEnd/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/FrontEnd/js/charts-home.js"></script>
<script src="~/FrontEnd/lib/Login.js"></script>
<script src="~/FrontEnd/lib/SendMessage.js"></script>
<script src="~/FrontEnd/lib/fnc_jaime.js"></script>
<script src="~/FrontEnd/lib/Commentaire.js"></script>


<script src="summernote.js"></script>


<script src="~/FrontEnd/lib/MEFPost.js"></script>
<script src="~/FrontEnd/js/front.js"></script>



<!-- include summernote css/js -->
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

@RenderSection("scripts", required: false)
</html>